# Generated by Django 5.0.6 on 2024-06-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porject',
            new_name='Project',
        ),
    ]
